// This file is automatically generated. Modifying its content manually is discouraged.
import React from 'react'
import { registerIcon } from '@harnessio/svg-icon'
import type { IconProps } from '@harnessio/svg-icon-react'
import { Icon } from '@harnessio/svg-icon-react'

const name = 'sound-low-solid/noir'

registerIcon(
  name,
  `<svg width="24" height="24" fill="none" stroke-width="1.5" viewBox="0 0 24 24"><path fill="currentColor" fill-rule="evenodd" d="M18.97 6.97a.75.75 0 0 1 1.06 0l-.53.53.53-.53h.001l.001.002.003.002.007.007.02.02.062.069c.05.057.12.138.201.241A6.87 6.87 0 0 1 21.75 11.5a6.87 6.87 0 0 1-1.425 4.189 5 5 0 0 1-.264.31l-.02.02-.006.007-.003.002v.001h-.001l-.51-.508.51.51a.75.75 0 1 1-1.061-1.061l.53.53-.53-.53h-.001v.001l-.002.001.005-.005.033-.036q.048-.052.139-.167a5.37 5.37 0 0 0 .448-5.843 5 5 0 0 0-.448-.685 3 3 0 0 0-.172-.203l-.005-.005a.75.75 0 0 1 .003-1.058m-5.933-3.574c1.163-.767 2.713.068 2.713 1.461v14.286c0 1.394-1.55 2.228-2.713 1.461l-6-3.955a.25.25 0 0 0-.137-.042H4a2.75 2.75 0 0 1-2.75-2.75v-3.714A2.75 2.75 0 0 1 4 7.393h2.9a.25.25 0 0 0 .138-.041z" clip-rule="evenodd"/></svg>`
)

export function SoundLowSolid(props: IconProps) {
  return <Icon name={name} {...props} />
}

SoundLowSolid.prototype.name = name
